name: Tests PassGuard using CI process

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app
      - name: Build & Test
        run: xcodebuild test -scheme PassGuard -project PassGuard/PassGuard.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14'
